### ISSUE TITLE
下载错误

### ISSUE THREAD

**Issue by TeslaLyon** [kun775/douyinhelper#1]
日志如下，是不是接口的参数变了？

**************************************************
               抖音下载小助手
     作者: HuangSK  Date: 2021-01-21 13:14
**************************************************
---配置的用户列表为:
https://v.douyin.com/J7vrTBr/
---保存的目录为:./Download/
---历史下载共 0 个视频
是否确认下载上述链接中的视频? Y/n:y
正在解析下载 https://v.douyin.com/J7vrTBr/
---获取sec_uid成功: MS4wLjABAAAAE3VPyGq8mODgSwz-NYglIKAlWTouvHprRLKizQe2hRM
Traceback (most recent call last):..
  File "/Users/liangshuo/code/py-project/douyinhelper/douyin.py", line 222, in <module>
    app.hello().run()
  File "/Users/liangshuo/code/py-project/douyinhelper/douyin.py", line 176, in run
    self.get_video_by_url(url)
  File "/Users/liangshuo/code/py-project/douyinhelper/douyin.py", line 190, in get_video_by_url
    nickname, video_list, max_cursor, has_more = self.get_video_urls(sec_uid, max_cursor)
  File "/Users/liangshuo/code/py-project/douyinhelper/douyin.py", line 102, in get_video_urls
    'desc': re.sub(r'[\/:*?"<>|]', '', item['desc']) if item['desc'] else '无标题' + str(int(time.time())),
NameError: name 'time' is not defined

**Comment by kun775** [comment]
没有，只是我删了一个引用，你手动添加import time就行了，我以为我没用到time
